//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSearch.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppSearch.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Search.
        /// </summary>
        internal static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apps.
        /// </summary>
        internal static string AppsDirName {
            get {
                return ResourceManager.GetString("AppsDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelName {
            get {
                return ResourceManager.GetString("CancelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to config.
        /// </summary>
        internal static string ConfigFileName {
            get {
                return ResourceManager.GetString("ConfigFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http{0}://{1}{2}.softsystem.pl:{3}/gcm/GcmWebServices/.
        /// </summary>
        internal static string DefaultWebServicesUrl {
            get {
                return ResourceManager.GetString("DefaultWebServicesUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BEWARE!
        ///Config file will be override after application close!.
        /// </summary>
        internal static string EditConfigFileWarning {
            get {
                return ResourceManager.GetString("EditConfigFileWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditText {
            get {
                return ResourceManager.GetString("EditText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target path is empty.
        /// </summary>
        internal static string EmptyTargetPath {
            get {
                return ResourceManager.GetString("EmptyTargetPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url path is empty.
        /// </summary>
        internal static string EmptyUrl {
            get {
                return ResourceManager.GetString("EmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enviroment.
        /// </summary>
        internal static string Enviroment {
            get {
                return ResourceManager.GetString("Enviroment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Tree View.
        /// </summary>
        internal static string HideTreeView {
            get {
                return ResourceManager.GetString("HideTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https?.
        /// </summary>
        internal static string HttpsText {
            get {
                return ResourceManager.GetString("HttpsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linux.
        /// </summary>
        internal static string LinuxName {
            get {
                return ResourceManager.GetString("LinuxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lxc.
        /// </summary>
        internal static string LinuxUrlPrefix {
            get {
                return ResourceManager.GetString("LinuxUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local.
        /// </summary>
        internal static string LocalEnvName {
            get {
                return ResourceManager.GetString("LocalEnvName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to log.txt.
        /// </summary>
        internal static string LoggerFileName {
            get {
                return ResourceManager.GetString("LoggerFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name: .
        /// </summary>
        internal static string NameText {
            get {
                return ResourceManager.GetString("NameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        internal static string NoClientName {
            get {
                return ResourceManager.GetString("NoClientName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path:.
        /// </summary>
        internal static string PathName {
            get {
                return ResourceManager.GetString("PathName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port (1024:49151):.
        /// </summary>
        internal static string PortName {
            get {
                return ResourceManager.GetString("PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SaveName {
            get {
                return ResourceManager.GetString("SaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search: .
        /// </summary>
        internal static string SearchLabel {
            get {
                return ResourceManager.GetString("SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Config.
        /// </summary>
        internal static string ShowConfig {
            get {
                return ResourceManager.GetString("ShowConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Tree View.
        /// </summary>
        internal static string ShowTreeView {
            get {
                return ResourceManager.GetString("ShowTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System:.
        /// </summary>
        internal static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0}.
        /// </summary>
        internal static string TaskEnded {
            get {
                return ResourceManager.GetString("TaskEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task {0} on {1}:{2}. Ping to: {3}.
        /// </summary>
        internal static string TaskEndedOnPing {
            get {
                return ResourceManager.GetString("TaskEndedOnPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unknow.
        /// </summary>
        internal static string Unknow {
            get {
                return ResourceManager.GetString("Unknow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows.
        /// </summary>
        internal static string WindowsName {
            get {
                return ResourceManager.GetString("WindowsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wp.
        /// </summary>
        internal static string WindowsUrlPrefix {
            get {
                return ResourceManager.GetString("WindowsUrlPrefix", resourceCulture);
            }
        }
    }
}
