/*
Deployment script for D:\PROJECTS\C#\AIT\AITDBLIB\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\PROJECTS\C#\AIT\AITDBLIB\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\PROJECTS\C_\AIT\AITDBLIB\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\NorArax NeflinOwl\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\NorArax NeflinOwl\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Starting rebuilding table [dbo].[AitPersons]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_AitPersons] (
    [prnID]       INT           IDENTITY (1, 1) NOT NULL,
    [prnLogin]    NVARCHAR (50) NOT NULL,
    [prnEmail]    NVARCHAR (50) NOT NULL,
    [prnPassword] NVARCHAR (50) NOT NULL,
    PRIMARY KEY CLUSTERED ([prnID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[AitPersons])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AitPersons] ON;
        INSERT INTO [dbo].[tmp_ms_xx_AitPersons] ([prnID], [prnLogin], [prnEmail], [prnPassword])
        SELECT   [prnID],
                 [prnLogin],
                 [prnEmail],
                 [prnPassword]
        FROM     [dbo].[AitPersons]
        ORDER BY [prnID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AitPersons] OFF;
    END

DROP TABLE [dbo].[AitPersons];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_AitPersons]', N'AitPersons';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[AitPersonsDetails]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_AitPersonsDetails] (
    [prdID]       INT           IDENTITY (1, 1) NOT NULL,
    [prdPersonID] INT           NOT NULL,
    [prdFName]    NVARCHAR (10) NOT NULL,
    [prdLName]    NVARCHAR (30) NOT NULL,
    [prdBDate]    DATE          NOT NULL,
    [prdPesel]    NUMERIC (11)  NOT NULL,
    PRIMARY KEY CLUSTERED ([prdID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[AitPersonsDetails])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AitPersonsDetails] ON;
        INSERT INTO [dbo].[tmp_ms_xx_AitPersonsDetails] ([prdID], [prdPersonID], [prdFName], [prdLName], [prdBDate], [prdPesel])
        SELECT   [prdID],
                 [prdPersonID],
                 [prdFName],
                 [prdLName],
                 [prdBDate],
                 [prdPesel]
        FROM     [dbo].[AitPersonsDetails]
        ORDER BY [prdID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AitPersonsDetails] OFF;
    END

DROP TABLE [dbo].[AitPersonsDetails];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_AitPersonsDetails]', N'AitPersonsDetails';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[AitQuickNotes]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_AitQuickNotes] (
    [qknID]       INT            IDENTITY (1, 1) NOT NULL,
    [qknPersonID] INT            NOT NULL,
    [qknTitle]    NVARCHAR (50)  NOT NULL,
    [qknNote]     NVARCHAR (MAX) NOT NULL,
    [qknCDate]    DATETIME       NOT NULL,
    PRIMARY KEY CLUSTERED ([qknID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[AitQuickNotes])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AitQuickNotes] ON;
        INSERT INTO [dbo].[tmp_ms_xx_AitQuickNotes] ([qknID], [qknPersonID], [qknTitle], [qknNote], [qknCDate])
        SELECT   [qknID],
                 [qknPersonID],
                 [qknTitle],
                 [qknNote],
                 [qknCDate]
        FROM     [dbo].[AitQuickNotes]
        ORDER BY [qknID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_AitQuickNotes] OFF;
    END

DROP TABLE [dbo].[AitQuickNotes];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_AitQuickNotes]', N'AitQuickNotes';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Update complete.';


GO
