//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string ABOUT_HEADER {
            get {
                return ResourceManager.GetString("ABOUT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account was activated.
        /// </summary>
        internal static string ACC_ACTIVATED {
            get {
                return ResourceManager.GetString("ACC_ACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is block! Contact to administations..
        /// </summary>
        internal static string ACC_BLOCED {
            get {
                return ResourceManager.GetString("ACC_BLOCED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is not activated!.
        /// </summary>
        internal static string ACC_NOACTIVATED {
            get {
                return ResourceManager.GetString("ACC_NOACTIVATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Code for &apos;{0}&apos;.
        /// </summary>
        internal static string ACT_CODE_FOR {
            get {
                return ResourceManager.GetString("ACT_CODE_FOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        internal static string ACTIVATION_CODE {
            get {
                return ResourceManager.GetString("ACTIVATION_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your activation code: {0}..
        /// </summary>
        internal static string ACTIVATION_EMAIL_CONTENT {
            get {
                return ResourceManager.GetString("ACTIVATION_EMAIL_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Activation Request.
        /// </summary>
        internal static string ACTIVATION_EMAIL_TITLE {
            get {
                return ResourceManager.GetString("ACTIVATION_EMAIL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .ait.
        /// </summary>
        internal static string AIT_EXT {
            get {
                return ResourceManager.GetString("AIT_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait, Application Inistalization....
        /// </summary>
        internal static string APP_INIT {
            get {
                return ResourceManager.GetString("APP_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AIT Nano.
        /// </summary>
        internal static string APP_NAME {
            get {
                return ResourceManager.GetString("APP_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application starting....
        /// </summary>
        internal static string APP_START {
            get {
                return ResourceManager.GetString("APP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait Almost Completed....
        /// </summary>
        internal static string APP_STARTCOMPLETED {
            get {
                return ResourceManager.GetString("APP_STARTCOMPLETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cache.
        /// </summary>
        internal static string CACHE_FILE {
            get {
                return ResourceManager.GetString("CACHE_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CANCEL {
            get {
                return ResourceManager.GetString("CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to cancel?.
        /// </summary>
        internal static string CANCEL_QUESTION {
            get {
                return ResourceManager.GetString("CANCEL_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Theme.
        /// </summary>
        internal static string CHANGETHEME_HEADER {
            get {
                return ResourceManager.GetString("CHANGETHEME_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string CLEAR {
            get {
                return ResourceManager.GetString("CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close All Windows.
        /// </summary>
        internal static string CLOSEALL_HEADER {
            get {
                return ResourceManager.GetString("CLOSEALL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is empty!.
        /// </summary>
        internal static string CODE_EMPTY {
            get {
                return ResourceManager.GetString("CODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code is incorect!.
        /// </summary>
        internal static string CODE_INCORECT {
            get {
                return ResourceManager.GetString("CODE_INCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in database. Not find activation code!.
        /// </summary>
        internal static string CODE_NOTFIND {
            get {
                return ResourceManager.GetString("CODE_NOTFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content is empty!.
        /// </summary>
        internal static string CONTENT_EMPTY {
            get {
                return ResourceManager.GetString("CONTENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating account success.
        /// </summary>
        internal static string CREATE_ACCSUCC {
            get {
                return ResourceManager.GetString("CREATE_ACCSUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Note.
        /// </summary>
        internal static string CREATE_NEW_NOTE {
            get {
                return ResourceManager.GetString("CREATE_NEW_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create:.
        /// </summary>
        internal static string CREATE_S {
            get {
                return ResourceManager.GetString("CREATE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create SHA256 Hash.
        /// </summary>
        internal static string CREATESHA256HASH_HEADER {
            get {
                return ResourceManager.GetString("CREATESHA256HASH_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .crypt.
        /// </summary>
        internal static string CRYPT_EXT {
            get {
                return ResourceManager.GetString("CRYPT_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypt Plain Text.
        /// </summary>
        internal static string CRYPTPLAINTEXT_HEADER {
            get {
                return ResourceManager.GetString("CRYPTPLAINTEXT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string DASHBOARD_HEADER {
            get {
                return ResourceManager.GetString("DASHBOARD_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Databases.
        /// </summary>
        internal static string DATABASES_SUBPATH {
            get {
                return ResourceManager.GetString("DATABASES_SUBPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string DATE_S {
            get {
                return ResourceManager.GetString("DATE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypt Crypt Text.
        /// </summary>
        internal static string DECRYPTCRYPTTEXT_HEADER {
            get {
                return ResourceManager.GetString("DECRYPTCRYPTTEXT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DELETE_BTNCONTENT {
            get {
                return ResourceManager.GetString("DELETE_BTNCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful delete {0} elements..
        /// </summary>
        internal static string DELETE_SUCC {
            get {
                return ResourceManager.GetString("DELETE_SUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detached.
        /// </summary>
        internal static string DETACHED {
            get {
                return ResourceManager.GetString("DETACHED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detach.
        /// </summary>
        internal static string DETACHED_BTNCONTENT {
            get {
                return ResourceManager.GetString("DETACHED_BTNCONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful detached {0} elements..
        /// </summary>
        internal static string DETACHED_SUCC {
            get {
                return ResourceManager.GetString("DETACHED_SUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to delete: {0}. {1}Fill reason and save. .
        /// </summary>
        internal static string DIALOG_DELETE_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files to detached: {0}. {1}Fill reason and save..
        /// </summary>
        internal static string DIALOG_DETACHED_TITLE {
            get {
                return ResourceManager.GetString("DIALOG_DETACHED_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EDIT_HEADER {
            get {
                return ResourceManager.GetString("EDIT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorect Email!.
        /// </summary>
        internal static string EMAIL_INCORECT {
            get {
                return ResourceManager.GetString("EMAIL_INCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required!.
        /// </summary>
        internal static string EMAIL_REQUIRED {
            get {
                return ResourceManager.GetString("EMAIL_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main send.
        /// </summary>
        internal static string EMAIL_SEND {
            get {
                return ResourceManager.GetString("EMAIL_SEND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .err.
        /// </summary>
        internal static string ERR_EXT {
            get {
                return ResourceManager.GetString("ERR_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ERROR {
            get {
                return ResourceManager.GetString("ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} errors handle. Check logs!.
        /// </summary>
        internal static string ERROR_HANDLEINFO {
            get {
                return ResourceManager.GetString("ERROR_HANDLEINFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No hadle error detected. Check log!.
        /// </summary>
        internal static string ERROR_NOHANDLE {
            get {
                return ResourceManager.GetString("ERROR_NOHANDLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string EXCEPTION {
            get {
                return ResourceManager.GetString("EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string EXIT_HEADER {
            get {
                return ResourceManager.GetString("EXIT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string FILE_HEADER {
            get {
                return ResourceManager.GetString("FILE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string HELP_HEADER {
            get {
                return ResourceManager.GetString("HELP_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your host was locked by admin!.
        /// </summary>
        internal static string HOST_LOCKED {
            get {
                return ResourceManager.GetString("HOST_LOCKED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID don&apos;t containt 2 separators!.
        /// </summary>
        internal static string ID_FORMATINCORECT {
            get {
                return ResourceManager.GetString("ID_FORMATINCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID length must equals 15!.
        /// </summary>
        internal static string ID_LENINCORECT {
            get {
                return ResourceManager.GetString("ID_LENINCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID postfix is not number!.
        /// </summary>
        internal static string ID_NUMBERMISING {
            get {
                return ResourceManager.GetString("ID_NUMBERMISING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID is required!.
        /// </summary>
        internal static string ID_REQUIRED {
            get {
                return ResourceManager.GetString("ID_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string INFORMATION {
            get {
                return ResourceManager.GetString("INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Init Main Window.
        /// </summary>
        internal static string INIT {
            get {
                return ResourceManager.GetString("INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization....
        /// </summary>
        internal static string INIT_WINDOW {
            get {
                return ResourceManager.GetString("INIT_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name &apos;{0}&apos; not find.
        /// </summary>
        internal static string INVALID_ACCOUNT_NAME {
            get {
                return ResourceManager.GetString("INVALID_ACCOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You pass invalid lucky number: {0}.
        /// </summary>
        internal static string INVALID_LOTTO_NUMBER {
            get {
                return ResourceManager.GetString("INVALID_LOTTO_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .json.
        /// </summary>
        internal static string JSON_EXT {
            get {
                return ResourceManager.GetString("JSON_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keylogger.
        /// </summary>
        internal static string KEYLOGGER {
            get {
                return ResourceManager.GetString("KEYLOGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .klg.
        /// </summary>
        internal static string KEYLOGGER_EXT {
            get {
                return ResourceManager.GetString("KEYLOGGER_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Empty.
        /// </summary>
        internal static string LIST_EMPTY {
            get {
                return ResourceManager.GetString("LIST_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalCache.
        /// </summary>
        internal static string LOCALCACHE_SUBPATH {
            get {
                return ResourceManager.GetString("LOCALCACHE_SUBPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .log.
        /// </summary>
        internal static string LOG_EXT {
            get {
                return ResourceManager.GetString("LOG_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        internal static string LOGDIR_SUBPATH {
            get {
                return ResourceManager.GetString("LOGDIR_SUBPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is empty!.
        /// </summary>
        internal static string LOGIN_EMPTY {
            get {
                return ResourceManager.GetString("LOGIN_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is already exists in system, please pass another!.
        /// </summary>
        internal static string LOGIN_EXIST {
            get {
                return ResourceManager.GetString("LOGIN_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with this login not find!.
        /// </summary>
        internal static string LOGIN_NOEXIST {
            get {
                return ResourceManager.GetString("LOGIN_NOEXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is required!.
        /// </summary>
        internal static string LOGIN_REQUIRED {
            get {
                return ResourceManager.GetString("LOGIN_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login success.
        /// </summary>
        internal static string LOGIN_SUCC {
            get {
                return ResourceManager.GetString("LOGIN_SUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login is too short!.
        /// </summary>
        internal static string LOGIN_TOOSHORT {
            get {
                return ResourceManager.GetString("LOGIN_TOOSHORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string LOGOUT_HEADER {
            get {
                return ResourceManager.GetString("LOGOUT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out success.
        /// </summary>
        internal static string LOGOUT_SUCC {
            get {
                return ResourceManager.GetString("LOGOUT_SUCC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto Lucky Numbers Array:.
        /// </summary>
        internal static string LOTTO_LUCKYNUMBERS_S {
            get {
                return ResourceManager.GetString("LOTTO_LUCKYNUMBERS_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto Note.
        /// </summary>
        internal static string LOTTO_NOTE {
            get {
                return ResourceManager.GetString("LOTTO_NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        internal static string MESSAGE {
            get {
                return ResourceManager.GetString("MESSAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate.
        /// </summary>
        internal static string NAV_HEADER {
            get {
                return ResourceManager.GetString("NAV_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Note.
        /// </summary>
        internal static string NEWNOTE_HEADER {
            get {
                return ResourceManager.GetString("NEWNOTE_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string NOTE {
            get {
                return ResourceManager.GetString("NOTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Content.
        /// </summary>
        internal static string NOTE_CONTENT {
            get {
                return ResourceManager.GetString("NOTE_CONTENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string NOTE_DESC {
            get {
                return ResourceManager.GetString("NOTE_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .note.
        /// </summary>
        internal static string NOTE_EXT {
            get {
                return ResourceManager.GetString("NOTE_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Tree View:.
        /// </summary>
        internal static string NOTE_TREEVIEW_S {
            get {
                return ResourceManager.GetString("NOTE_TREEVIEW_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes Manager.
        /// </summary>
        internal static string NOTEMANAGER_HEADER {
            get {
                return ResourceManager.GetString("NOTEMANAGER_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obj.
        /// </summary>
        internal static string OBJDIR_SUBPATH {
            get {
                return ResourceManager.GetString("OBJDIR_SUBPATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        internal static string OFFLINE_STATUS {
            get {
                return ResourceManager.GetString("OFFLINE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        internal static string ONLINE_STATUS {
            get {
                return ResourceManager.GetString("ONLINE_STATUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is empty!.
        /// </summary>
        internal static string PASS_EMPTY {
            get {
                return ResourceManager.GetString("PASS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account with this password not find!.
        /// </summary>
        internal static string PASS_NOFIND {
            get {
                return ResourceManager.GetString("PASS_NOFIND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passowd and repeat password is not identical!.
        /// </summary>
        internal static string PASS_REPPASS_INCORECT {
            get {
                return ResourceManager.GetString("PASS_REPPASS_INCORECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required!.
        /// </summary>
        internal static string PASS_REQUIRED {
            get {
                return ResourceManager.GetString("PASS_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is too weak!.
        /// </summary>
        internal static string PASS_TOOWEAK {
            get {
                return ResourceManager.GetString("PASS_TOOWEAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .patch.
        /// </summary>
        internal static string PATCH_EXT {
            get {
                return ResourceManager.GetString("PATCH_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid table prefix!.
        /// </summary>
        internal static string PREFIX_INVALID {
            get {
                return ResourceManager.GetString("PREFIX_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process....
        /// </summary>
        internal static string PROCESS {
            get {
                return ResourceManager.GetString("PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string QUERY {
            get {
                return ResourceManager.GetString("QUERY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query.
        /// </summary>
        internal static string QUERY_HEADER {
            get {
                return ResourceManager.GetString("QUERY_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Query Builder.
        /// </summary>
        internal static string QUERYBULIDER_HEADER {
            get {
                return ResourceManager.GetString("QUERYBULIDER_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QUESTION {
            get {
                return ResourceManager.GetString("QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo.
        /// </summary>
        internal static string REDO_HEADER {
            get {
                return ResourceManager.GetString("REDO_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string REGISTER_TITLE {
            get {
                return ResourceManager.GetString("REGISTER_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Product.
        /// </summary>
        internal static string REGISTERPRODUCT_HEADER {
            get {
                return ResourceManager.GetString("REGISTERPRODUCT_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some window was open..
        /// </summary>
        internal static string REOPEN_SOME_WINDOW {
            get {
                return ResourceManager.GetString("REOPEN_SOME_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All window is already open..
        /// </summary>
        internal static string REOPEN_ZERO_WINDOW {
            get {
                return ResourceManager.GetString("REOPEN_ZERO_WINDOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samethings go wrong!.
        /// </summary>
        internal static string SAMETHING_WRONG {
            get {
                return ResourceManager.GetString("SAMETHING_WRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string SAVE {
            get {
                return ResourceManager.GetString("SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save?.
        /// </summary>
        internal static string SAVE_QUESTION {
            get {
                return ResourceManager.GetString("SAVE_QUESTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string SETTINGS_HEADER {
            get {
                return ResourceManager.GetString("SETTINGS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string SETUP_HEADER {
            get {
                return ResourceManager.GetString("SETUP_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sheduler.
        /// </summary>
        internal static string SHEDULER {
            get {
                return ResourceManager.GetString("SHEDULER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string SHOWALL_HEADER {
            get {
                return ResourceManager.GetString("SHOWALL_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: opening {0}.
        /// </summary>
        internal static string STATUS_OPENING_S {
            get {
                return ResourceManager.GetString("STATUS_OPENING_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: proccess.
        /// </summary>
        internal static string STATUS_PROCESSING_S {
            get {
                return ResourceManager.GetString("STATUS_PROCESSING_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Ready.
        /// </summary>
        internal static string STATUS_READY {
            get {
                return ResourceManager.GetString("STATUS_READY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task.
        /// </summary>
        internal static string TASK {
            get {
                return ResourceManager.GetString("TASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string TOOLS_HEADER {
            get {
                return ResourceManager.GetString("TOOLS_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trace.
        /// </summary>
        internal static string TRACE {
            get {
                return ResourceManager.GetString("TRACE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .trace.
        /// </summary>
        internal static string TRC_EXT {
            get {
                return ResourceManager.GetString("TRC_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .txt.
        /// </summary>
        internal static string TXT_EXT {
            get {
                return ResourceManager.GetString("TXT_EXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type: .
        /// </summary>
        internal static string TYPE_S {
            get {
                return ResourceManager.GetString("TYPE_S", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string UNDEFINED {
            get {
                return ResourceManager.GetString("UNDEFINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo.
        /// </summary>
        internal static string UNDO_HEADER {
            get {
                return ResourceManager.GetString("UNDO_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string UNKNOWN {
            get {
                return ResourceManager.GetString("UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lotto Lucky Number {0}.
        /// </summary>
        internal static string USER_LOTTONUMBER {
            get {
                return ResourceManager.GetString("USER_LOTTONUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string VIEW_HEADER {
            get {
                return ResourceManager.GetString("VIEW_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit application?.
        /// </summary>
        internal static string WANT_EXIT {
            get {
                return ResourceManager.GetString("WANT_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WARNING {
            get {
                return ResourceManager.GetString("WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your network connection.
        /// </summary>
        internal static string WEB_CONNECTION_ERROR {
            get {
                return ResourceManager.GetString("WEB_CONNECTION_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Email address is not exists.
        /// </summary>
        internal static string WRONG_EMAIL {
            get {
                return ResourceManager.GetString("WRONG_EMAIL", resourceCulture);
            }
        }
    }
}
